# Web profiles
spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:memory
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: create
